#!/bin/sh
#----------------------------------------------------------------------
# smeserver-update daily tasks
# Copyright (C) 2024 Koozali Foundation, Inc.
# Copyright (C) 2005 Gordon Rowell <gordonr@gormand.com.au>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License or more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#----------------------------------------------------------------------

dnf_status=$(/sbin/e-smith/db configuration getprop dnf status|| echo "disabled")

[ $dnf_status = 'enabled' ] || exit 0

/usr/bin/systemctl restart dnf.service

