#!/bin/bash
#----------------------------------------------------------------------
# copyright (C) 2025 Koozali Foundation Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#----------------------------------------------------------------------

# set mariadb as disabled, as we use rpm directly from MariaDB
printf '[mariadb]
name=mariadb
stream=
profiles=
state=disabled' | crudini --merge /etc/dnf/modules.d/mariadb.module

# set perl 5.26
printf '[perl]
name=perl
stream=5.26
profiles=
state=enabled' | crudini --merge /etc/dnf/modules.d/perl.module

# set php module to our default
printf '[php]
name=php
stream=remi-8.4
profiles=
state=enabled' | crudini --merge /etc/dnf/modules.d/php.module php

# set python to 3.6
printf '[python36]
name=python36
stream=3.6
profiles=
state=enabled' | crudini --merge /etc/dnf/modules.d/python36.module

# set redis 7.2
printf '[redis]
name=redis
stream=remi-7.2
profiles=
state=enabled' | crudini --merge /etc/dnf/modules.d/redis.module

# set virt
printf '[virt]
name=virt
stream=rhel
profiles=
state=enabled' | crudini --merge /etc/dnf/modules.d/virt.module

# set perl-DBD-MySQL
printf '[perl-DBD-MySQL]
name=perl-DBD-MySQL
stream=4.046
profiles=
state=enabled' | crudini --merge /etc/dnf/modules.d/perl-DBD-MySQL.module

printf '[perl-DBI]
name=perl-DBI
stream=1.641
profiles=
state=enabled' | crudini --merge /etc/dnf/modules.d/perl-DBI.module

# set composer
printf '[composer]
name=composer
stream=2
profiles=
state=enabled' | crudini --merge /etc/dnf/modules.d/composer.module

# set container-tools
printf '[container-tools]
name=container-tools
stream=rhel8
profiles=
state=enabled' | crudini --merge /etc/dnf/modules.d/container-tools.module

# set squid
printf '[squid]
name=squid
stream=4
profiles=
state=enabled' | crudini --merge /etc/dnf/modules.d/squid.module
